#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if echo "$commit_msg" | grep -qE "(--skip-changelog|--sc)$"; then
    echo "Skipping changelog check..."
else
    npm run check-changelog
fi